baseURL = 'http://localhost'
languageCode = 'hu'
defaultContentLanguage = 'hu'
title = 'Szigma'
canonifyURLs = true
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
  authors = 'authors'
  headings = 'heading' 

[related]
  includeNewer = true 
  threshold = 0
  toLower = true 
[[related.indices]]
  name = 'authors'
  weight = 80 
[[related.indices]]
  name = 'heading'
  weight = 80 
[[related.indices]]
  name = 'title'
  weight = 10
[[related.indices]]
  name = 'date'
  threshold = "30d"
  weight = 10
[[related.indices]]
  name = 'summary'
  weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'xcode-dark'
    tabWidth = 4